<a href="https://colab.research.google.com/github/ham952/Calculator-bot/blob/main/Assignmnet_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment : 3
Hamza Rafique



22030019

In [2]:
"""
################################################################################
#                                                                              #
# EE 567 - Multi Agents System                                                 #
# Dr Hasaan Jaleel - Fall 2022                                                 #
#                                                                              #
# Programming Assignment : 3                                                   #
# Prgramming LLL and Gradient Dynamixs                                         #
#                                                                              #
# version : 1.1.0                                                              #
# model   : 2022.11                                                            #
# author  : Hamza Rafique                                                      #
# email   : hamza.rafique@lums.edu.pk                                          #
# web     : https://github.com/ham952                                          #
#                                                                              #
# Changelog (ver 1.0.0):                                                       #
#   1.                    #
#   2.                                                   #
#                                                                              #
################################################################################  
"""

'\n################################################################################\n#                                                                              #\n# EE 567 - Multi Agents System                                                 #\n# Dr Hasaan Jaleel - Fall 2022                                                 #\n#                                                                              #\n# Programming Assignment : 3                                                   #\n# Prgramming LLL and Gradient Dynamixs                                         #\n#                                                                              #\n# version : 1.1.0                                                              #\n# model   : 2022.11                                                            #\n# author  : Hamza Rafique                                                      #\n# email   : hamza.rafique@lums.edu.pk                                          #\n# web     : h

In [1]:
import numpy as np

In [ ]:
################################################
#                                              #
# LLL Dynamics for n x m matrix with 2 players #
#                                              #
################################################

def LLLmatrix(G, tau, T):
    
    """Script that simulates the LLL dynamics for 2 players in 
    a Strategic Game.

    Args:
        G (array): the global score game matrix e.g 
        tau (int): temperature e.g 0.2
        T (integer): max number of iterations   e.g 300

    Returns:
        Freqs (array) = a matrix indicating the % time played for each joint action
    """

In [51]:
G = np.array(([1,2,3],[5,10,3],[9,50,1]))

# n : number of actions of row player
# m : number of actions of col player
n,m = np.shape(G)

# Initialization
t = 0
action_row = np.random.randint(0,n)
action_col = np.random.randint(0,m)

Freqs = np.zeros((n,m))
Freqs[action_row,action_col]  = Freqs[action_row,action_col] + 1

In [53]:
Freqs[action_row,action_col]  = Freqs[action_row,action_col] + 1
print(action_row,action_col)
print(Freqs)

1 1
[[0. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


In [64]:
tau = 0.1
y = np.zeros((n))
for i in range(n):
  x = G[i][action_col] - G[0][action_col]
  y[i] = np.exp(x/tau)
  print(x,y[i])
s = y/np.sum(y)
print(s)

f = np.zeros((n+1))
# f[0] = s[0] 
for k in range(1,n+1):
  f[k] = f[k-1] + s[k-1]

print(f)

0 1.0
8 5.54062238439351e+34
48 2.8930191842539453e+208
[3.4565965e-209 1.9151696e-174 1.0000000e+000]
[0.0000000e+000 3.4565965e-209 1.9151696e-174 1.0000000e+000]
